import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "ai2wallet-sdk/dist/client/style.css";
import { Ai2walletProvider } from "ai2wallet-sdk";

type ReownNetwork = 'testnet' | 'mainnet'
const reown_project_id = process.env.REOWN_PROJECT_ID as string;
const reown_network = process.env.REOWN_NETWORK as ReownNetwork;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Ai2walletProvider reown={{ projectId: reown_project_id, network: reown_network }}>{children}</Ai2walletProvider>
      </body>
    </html>
  );
}
